In [68]:
import pandas as pd

In [69]:
import numpy as np

Importing dataset:

In [70]:
stud = pd.read_csv("../data/data.csv", sep=";")
stud.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

Pivot Tables (which are a summary of the raw data tables)

A raw table stores data.
A pivot table stores insights.

In [71]:
stud.pivot_table(index = "Target", columns = ["Marital status"], values = "Inflation rate", aggfunc = np.mean)

C:\Users\Raphael\AppData\Local\Temp\ipykernel_14436\2117831230.py:1: FutureWarning: The provided callable <function mean at 0x000002D3876AFBA0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  stud.pivot_table(index = "Target", columns = ["Marital status"], values = "Inflation rate", aggfunc = np.mean)

Marital status         1         2     3         4         5      6
Target
Dropout         1.282601  1.300559  1.40  1.269048  1.354545  0.875
Enrolled        1.220694  1.003846  2.55  1.593750 -0.333333  1.400
Graduate        1.193499  1.216216 -0.80  1.163636  2.181818 -0.300

In [72]:
stud.pivot_table(index = "Target", columns = ["Daytime/evening attendance\t","Marital status"], values = "Previous qualification (grade)", aggfunc = np.mean)

C:\Users\Raphael\AppData\Local\Temp\ipykernel_14436\3998725755.py:1: FutureWarning: The provided callable <function mean at 0x000002D3876AFBA0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  stud.pivot_table(index = "Target", columns = ["Daytime/evening attendance\t","Marital status"], values = "Previous qualification (grade)", aggfunc = np.mean)

Daytime/evening attendance	           0                                        \
Marital status                        1           2      3           4      5
Target
Dropout                      128.471774  130.476471    NaN  127.733333  120.0
Enrolled                     128.863415  133.296000    NaN  135.400000    NaN
Graduate                     132.313333  131.133784  120.0  138.388235  120.0

Daytime/evening attendance	                  1                                 \
Marital status                   6           1           2      3           4
Target
Dropout                      122.5  131.537736  129.937838  135.0  130.753333
Enrolled                     133.1  131.172607  129.177778  154.0  137.412500
Graduate                     133.1  134.495393  130.505405    NaN  126.593750

Daytime/evening attendance
Marital status                      5      6
Target
Dropout                      143.5500  133.1
Enrolled                     128.7000    NaN
Graduate                     132.1375    NaN

Importing jinja2 for HTML DataFrame rendering:

In [73]:
import sys
!{sys.executable} -m pip install -U jinja2

Requirement already satisfied: jinja2 in c:\users\raphael\appdata\local\programs\python\python313\lib\site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\raphael\appdata\local\programs\python\python313\lib\site-packages (from jinja2) (3.0.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Conditional Formatting (Styler: applymap vs apply)

Creating a simplified dataframe to illustrate the principle:

In [74]:
df = pd.DataFrame({
    "A": [9, -7, 5],
    "B": [-1, 3, -4]
})
df

   A  B
0  9 -1
1 -7  3
2  5 -4

Defining a function to apply color:

In [75]:
def color_positive_negative(val):
    color = "green" if val > 0 else "red"
    return "color : %s" % color

Applying color to DataFrame:

In [76]:
styled_df = df.style.applymap(color_positive_negative)
styled_df

C:\Users\Raphael\AppData\Local\Temp\ipykernel_14436\1306871635.py:1: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.applymap(color_positive_negative)

Defining the function that highlights the maximum and minimum values.

In [77]:
def highlight_max_min(s):
    is_max = s == s.max()
    is_min = s == s.min()
    return ["color : green" if v_max else "color : red" if v_min else "" for v_max, v_min in zip (is_max, is_min) ]

Applying conditional formatting:

In [78]:
styled_df = df.style.apply(highlight_max_min)
display(styled_df)

Creating new pivot table:

In [79]:
pivot_df = stud.pivot_table(index = "Marital status",
                columns = ["Target"],
                values = "Previous qualification (grade)",
                aggfunc = np.mean             
)

pivot_df

C:\Users\Raphael\AppData\Local\Temp\ipykernel_14436\33946072.py:1: FutureWarning: The provided callable <function mean at 0x000002D3876AFBA0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_df = stud.pivot_table(index = "Marital status",

Target             Dropout    Enrolled    Graduate
Marital status
1               131.216639  131.041111  134.381687
2               130.142458  131.157692  130.819595
3               135.000000  154.000000  120.000000
4               129.890476  136.406250  132.669697
5               141.409091  128.700000  128.827273
6               127.800000  133.100000  133.100000

In [80]:
def highlight_max_min(data):
    styles = data.copy()
    for col in data.columns:
        max_val = data[col].max()
        min_val = data[col].min()
        styles[col] = [ "background-color : lightgreen" if v == max_val else "background-color : yellow"
                       if v == min_val else "" for v in data[col]
                       ]
    return styles

In [81]:
styled_df = pivot_df.style.apply(highlight_max_min, axis=None)
display(styled_df)

Using the agg function in Pandas

Create dataset with numeric columns only:

In [82]:
stud_num = stud.select_dtypes(include="number")
stud_num.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0,0.000000,0,10.8,1.4,1.74
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,0,6,0,0,0.000000,0,10.8,1.4,1.74
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79

In [83]:
stud_num.agg(['sum', 'mean', 'min'])

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
sum,5214.000000,82592.000000,7644.000000,3.918179e+07,3941.000000,20252.000000,586681.300000,8287.000000,86542.000000,98546.000000,...,609.000000,2397.000000,27571.000000,35672.000000,19624.000000,45258.430117,665.000000,51168.600000,5432.800000,8.710000
mean,1.178571,18.669078,1.727848,8.856643e+03,0.890823,4.577758,132.613314,1.873192,19.561935,22.275316,...,0.137658,0.541817,6.232143,8.063291,4.435805,10.230206,0.150316,11.566139,1.228029,0.001969
min,1.000000,1.000000,0.000000,3.300000e+01,0.000000,1.000000,95.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000

In [84]:
def amplitude(series):
    return series.max() - series.min()

In [85]:
stud_num.agg(["sum","mean","min",amplitude])

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
sum,5214.000000,82592.000000,7644.000000,3.918179e+07,3941.000000,20252.000000,586681.300000,8287.000000,86542.000000,98546.000000,...,609.000000,2397.000000,27571.000000,35672.000000,19624.000000,45258.430117,665.000000,51168.600000,5432.800000,8.710000
mean,1.178571,18.669078,1.727848,8.856643e+03,0.890823,4.577758,132.613314,1.873192,19.561935,22.275316,...,0.137658,0.541817,6.232143,8.063291,4.435805,10.230206,0.150316,11.566139,1.228029,0.001969
min,1.000000,1.000000,0.000000,3.300000e+01,0.000000,1.000000,95.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
amplitude,5.000000,56.000000,9.000000,9.958000e+03,1.000000,42.000000,95.000000,108.000000,43.000000,43.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,8.600000,4.500000,7.570000

Combining Different Datasets

In [86]:
purchases = pd.DataFrame({
    "id_client" : ['AA00', 'AA00', 'BB01', 'BB01', 'BB01', 'CC02', 'CC02', 'CC02', 'CC02', 'CC02'],
    "purchase_date" : ['2023-01-01', '2023-01-05', '2023-01-10', '2023-01-15', '2023-01-20',
                    '2023-01-25', '2023-01-30', '2023-02-01', '2023-02-05', '2023-02-10'],
    "value_purchase" : [100, 150, 200, 250, 300, 350, 400, 450, 500, 550]
})

In [87]:
geolocation = pd.DataFrame({
    "id_client" : ['AA00', 'BB01', 'CC02', 'DD03', 'EE04'],
    "state" : ['São Paulo', 'São Paulo', 'Minas Gerais', 'Bahia', 'Pernambuco']
})

Total Purchase Value per Client

Group the purchases dataset by `id_cliente` and sum `valor_compra`

In [88]:
purchases_group = purchases.groupby("id_client")["value_purchase"].sum().reset_index()
purchases_group

  id_client  value_purchase
0      AA00             250
1      BB01             750
2      CC02            2250

Merge Purchase Totals with Client Location

Merge the aggregated purchases dataset with the geolocation dataset using `id_cliente`

In [89]:
purchases_group_geo = purchases_group.merge(geolocation, on = "id_client", how = "left")
purchases_group_geo

  id_client  value_purchase         state
0      AA00             250     São Paulo
1      BB01             750     São Paulo
2      CC02            2250  Minas Gerais

Total Purchase Value by State

Combine purchase data with location data and calculate total spending per state

In [90]:
purchases_group_geo = purchases_group_geo.groupby("state")["value_purchase"].sum().reset_index()
purchases_group_geo

          state  value_purchase
0  Minas Gerais            2250
1     São Paulo            1000

Creating Example DataFrames for Join Operations

In [91]:
df_A = pd.DataFrame({
    "Key" : [1, 2, 3],
    "Value_A" : ["A1", "A2", "A3"]
    })
df_A

   Key Value_A
0    1      A1
1    2      A2
2    3      A3

In [92]:
df_B =pd.DataFrame({
    "Key": [1, 3, 4],
    "Value_B": ["B1", "B3", "B4"]
})
df_B

   Key Value_B
0    1      B1
1    3      B3
2    4      B4

Left Join (Keeping All Records from the Left DataFrame)

In [93]:
left_join = df_A.merge(df_B, on = "Key", how = "left")
left_join

   Key Value_A Value_B
0    1      A1      B1
1    2      A2     NaN
2    3      A3      B3

Right Join (Keeping All Records from the Right DataFrame)

In [94]:
right_join = df_A.merge(df_B, on = "Key", how = "right")
right_join

   Key Value_A Value_B
0    1      A1      B1
1    3      A3      B3
2    4     NaN      B4

Inner Join (Keeping Only Matching Records)

In [95]:
inner_join = df_A.merge(df_B, on = "Key", how = "inner")
inner_join

   Key Value_A Value_B
0    1      A1      B1
1    3      A3      B3

Outer Join (Keeping All Records from Both DataFrames)

In [96]:
outer_join = df_A.merge(df_B, on = "Key", how = "outer")
outer_join

   Key Value_A Value_B
0    1      A1      B1
1    2      A2     NaN
2    3      A3      B3
3    4     NaN      B4

Concatenating DataFrames ( Also known as Stacking)

Creating two DataFrames for purchases made in the months of June and July as well as August and September

In [97]:
jun_jul = pd.DataFrame({
'id_cliente': ['AA01', 'BB02', 'AA01', 'CC03', 'BB02', 'DD04'],
'dt_compra': ['2023-06-05', '2023-06-15', '2023-06-25', '2023-07-05', '2023-07-15', '2023-07-25'],
'vl_compra': [200.50, 155.75, 333.60, 450.00, 300.10, 250.00]
})
jun_jul

  id_cliente   dt_compra  vl_compra
0       AA01  2023-06-05     200.50
1       BB02  2023-06-15     155.75
2       AA01  2023-06-25     333.60
3       CC03  2023-07-05     450.00
4       BB02  2023-07-15     300.10
5       DD04  2023-07-25     250.00

In [98]:
ago_set = pd.DataFrame({
'id_cliente': ['EE05', 'EE05', 'FF06', 'GG07'],
'dt_compra': ['2023-08-05', '2023-08-15', '2023-08-25', '2023-09-05'],
'vl_compra': [205.55, 233.75, 550.65, 320.82]
})
ago_set

  id_cliente   dt_compra  vl_compra
0       EE05  2023-08-05     205.55
1       EE05  2023-08-15     233.75
2       FF06  2023-08-25     550.65
3       GG07  2023-09-05     320.82

Concatenating the two DataFrames

In [99]:
df_concat = pd.concat([jun_jul, ago_set])
df_concat

  id_cliente   dt_compra  vl_compra
0       AA01  2023-06-05     200.50
1       BB02  2023-06-15     155.75
2       AA01  2023-06-25     333.60
3       CC03  2023-07-05     450.00
4       BB02  2023-07-15     300.10
5       DD04  2023-07-25     250.00
0       EE05  2023-08-05     205.55
1       EE05  2023-08-15     233.75
2       FF06  2023-08-25     550.65
3       GG07  2023-09-05     320.82

Creating discrete intervals with cut and qcut

In [100]:
df = pd.DataFrame({"value" : [1, 2, 3, 4, 5]})
df["bin"] = pd.cut(df["value"], bins = [0, 3, 5], labels = ["Low", "High"])
df

   value   bin
0      1   Low
1      2   Low
2      3   Low
3      4  High
4      5  High

Creating two equal intervals

In [101]:
df["equal bins"] = pd.cut(df["value"], bins = 3)
df

   value   bin      equal bins
0      1   Low  (0.996, 2.333]
1      2   Low  (0.996, 2.333]
2      3   Low  (2.333, 3.667]
3      4  High    (3.667, 5.0]
4      5  High    (3.667, 5.0]

Quantile-based binning with pd.qcut()

In [102]:
df = pd.DataFrame({"value" : [1, 2, 3, 4, 5]})
df["quantile_bin"] = pd.qcut(df["value"], q = 2, labels = ["Low", "High"])
df

   value quantile_bin
0      1          Low
1      2          Low
2      3          Low
3      4         High
4      5         High

In [103]:
df = pd.DataFrame({"value" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})
df["custom_quantile_bin"] = pd.qcut(df['value'], q=[0, 0.1, 0.5, 1])
df

   value custom_quantile_bin
0      1        (0.999, 1.9]
1      2          (1.9, 5.5]
2      3          (1.9, 5.5]
3      4          (1.9, 5.5]
4      5          (1.9, 5.5]
5      6         (5.5, 10.0]
6      7         (5.5, 10.0]
7      8         (5.5, 10.0]
8      9         (5.5, 10.0]
9     10         (5.5, 10.0]

Random sampling with df.sample()

In [104]:
stud = pd.read_csv("../data/pandas part 2 datasets/students/data.csv", sep=";")
sample = stud.sample(n = 10)
sample

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
1133,1,1,1,9500,1,1,145.0,1,19,1,...,0,8,8,8,15.162500,0,13.9,-0.3,0.79,Graduate
2139,1,1,1,9147,1,1,116.0,1,19,19,...,0,5,13,2,11.500000,0,9.4,-0.8,-3.12,Dropout
3110,1,42,1,171,1,1,132.0,1,1,1,...,0,0,0,0,0.000000,0,12.7,3.7,-1.70,Dropout
712,2,39,1,9085,1,1,133.1,1,37,37,...,0,5,6,5,11.600000,0,7.6,2.6,0.32,Graduate
1125,1,1,2,9670,1,1,144.0,1,37,38,...,0,5,5,4,13.000000,0,9.4,-0.8,-3.12,Graduate
1361,1,1,4,9500,1,1,139.0,1,37,38,...,0,8,8,7,13.331429,0,10.8,1.4,1.74,Graduate
3107,1,1,1,9500,1,1,118.0,1,1,19,...,0,8,8,8,14.756250,0,11.1,0.6,2.02,Graduate
270,1,44,1,9003,1,39,150.0,1,37,38,...,0,6,8,5,12.800000,0,13.9,-0.3,0.79,Graduate
3081,1,1,6,9500,1,1,122.0,1,19,37,...,0,8,8,8,12.575000,0,12.4,0.5,1.79,Graduate
3187,1,1,1,9500,1,1,135.0,1,19,19,...,0,7,8,0,0.000000,0,15.5,2.8,-4.06,Dropout

In [105]:
sample_10_perc = stud.sample(frac = 0.1)
sample_10_perc

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
1994,1,1,1,9254,1,1,133.0,1,19,9,...,0,6,12,0,0.000000,0,7.6,2.6,0.32,Dropout
3366,1,1,1,9991,0,1,122.0,1,37,37,...,0,5,10,3,12.000000,0,7.6,2.6,0.32,Enrolled
3862,1,1,1,9773,1,1,140.0,1,19,38,...,0,6,6,6,12.833333,0,12.7,3.7,-1.70,Graduate
2024,2,39,1,9991,0,1,120.0,1,37,37,...,0,5,9,4,11.750000,0,9.4,-0.8,-3.12,Enrolled
2068,1,18,4,9853,1,1,123.0,1,19,38,...,0,6,8,5,11.000000,0,15.5,2.8,-4.06,Enrolled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,1,1,1,9670,1,1,132.0,1,1,19,...,0,6,8,4,13.000000,0,12.4,0.5,1.79,Enrolled
20,1,1,3,171,1,1,122.0,1,1,1,...,0,0,0,0,0.000000,0,11.1,0.6,2.02,Graduate
1983,1,1,1,9500,1,1,147.0,1,38,19,...,0,7,7,6,13.966667,0,7.6,2.6,0.32,Graduate
567,1,17,4,9119,1,1,129.0,1,34,36,...,0,5,10,3,11.333333,4,7.6,2.6,0.32,Dropout
2218,1,7,1,9773,1,43,140.0,1,19,1,...,0,6,6,6,13.500000,0,11.1,0.6,2.02,Graduate

Identifying unique values and counts with unique() and nunique()

nunique returns the number of unique elements in the object, while unique returns the unique elements themselves

In [106]:
stud.Target.unique()

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

In [107]:
stud.Target.nunique()

3

Method 1: Identifying categorical vs numerical columns by data type (dtypes)

In [108]:
# List columns with data type 'object' (usually text or string)
categorical_features = stud.select_dtypes(include = ["object"]).columns.tolist()

In [109]:
# List columns with numeric data types (int and float)
numerical_features = stud.select_dtypes(exclude = ["object"]).columns.tolist()

Method 2: Identifying categorical vs numerical columns by number of unique values

In [110]:
# Assuming stud is your DataFrame and the threshold is 10 unique values
unique_counts = stud.nunique()

In [111]:
categorical_features = unique_counts[unique_counts <= 10].index.tolist()
numerical_features = unique_counts[unique_counts > 10].index.tolist()

Applying custom functions to data using apply() and lambda

apply() lets you run a custom function on each element of a Series or across rows/columns of a DataFrame. It’s useful when you need transformations or calculations that aren’t easily done with built-in pandas methods

In [112]:
df = pd.DataFrame({'A': [1, 2, 3, 4, 5]})

df['quadrado'] = df['A'].apply(lambda x: x**2)

df

   A  quadrado
0  1         1
1  2         4
2  3         9
3  4        16
4  5        25

In [113]:
df = pd.DataFrame({"A" : [1, 2, 3, 4, 5]})
df['square'] = df['A'].apply(lambda x: x**2)
df

   A  square
0  1       1
1  2       4
2  3       9
3  4      16
4  5      25

In [114]:
stud["new_GDP"] = stud["GDP"].apply(lambda x : x * 100)
stud[["GDP", "new_GDP"]].head()

    GDP  new_GDP
0  1.74    174.0
1  0.79     79.0
2  1.74    174.0
3 -3.12   -312.0
4  0.79     79.0

apply() can operate across columns (axis=0) or rows (axis=1), allowing you to apply functions in different directions of a DataFrame.

In [115]:
# Building a DataFrame for examples
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [116]:
# Mean of rows
df.apply(lambda row: row.mean(), axis=1)

0    4.0
1    5.0
2    6.0
dtype: float64

In [117]:
# Sum of columns
df.apply(lambda row: row.sum(), axis=0)

A     6
B    15
C    24
dtype: int64

Creating contingency tables with pd.crosstab() to analyze relationships between categorical variables

In [120]:
prod = pd.read_csv("../data/products.csv")
prod.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

Creates a table counting products by model_year and brand_id to see how production varies across years and brands

In [121]:
pd.crosstab(prod["model_year"], prod["brand_id"])

brand_id     1   2  3  4  5  6   7   8   9
model_year
2016        12   0  1  3  1  0   0   4   5
2017        16  10  0  0  0  0  23   8  28
2018        90   0  2  0  0  3   0  13  96
2019         0   0  0  0  0  0   0   0   6

How to see the total number of rows and columns

In [122]:
pd.crosstab(prod["model_year"], prod["brand_id"], margins = True)

brand_id      1   2  3  4  5  6   7   8    9  All
model_year
2016         12   0  1  3  1  0   0   4    5   26
2017         16  10  0  0  0  0  23   8   28   85
2018         90   0  2  0  0  3   0  13   96  204
2019          0   0  0  0  0  0   0   0    6    6
All         118  10  3  3  1  3  23  25  135  321

Row-wise percentage (each row sums to 1)

In [123]:
pd.crosstab(prod["model_year"], prod["brand_id"]).apply(lambda r: r/r.sum(), axis = 1)

brand_id,1,2,3,4,5,6,7,8,9
model_year,,,,,,,,,
2016,0.461538,0.000000,0.038462,0.115385,0.038462,0.000000,0.000000,0.153846,0.192308
2017,0.188235,0.117647,0.000000,0.000000,0.000000,0.000000,0.270588,0.094118,0.329412
2018,0.441176,0.000000,0.009804,0.000000,0.000000,0.014706,0.000000,0.063725,0.470588
2019,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000

Column-wise percentage (each column sums to 1)

In [124]:
pd.crosstab(prod['model_year'], prod['brand_id']).apply(lambda r: r / r.sum(), axis=0)

brand_id           1    2         3    4    5    6    7     8         9
model_year
2016        0.101695  0.0  0.333333  1.0  1.0  0.0  0.0  0.16  0.037037
2017        0.135593  1.0  0.000000  0.0  0.0  0.0  1.0  0.32  0.207407
2018        0.762712  0.0  0.666667  0.0  0.0  1.0  0.0  0.52  0.711111
2019        0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.00  0.044444

Detecting missing values with isna()

In [125]:
df = pd.DataFrame({
    'A': [1, 2, None, 4, 5],
    'B': ['A', None, 'C', None, 'E']
})

df

     A     B
0  1.0     A
1  2.0  None
2  NaN     C
3  4.0  None
4  5.0     E

In [126]:
df.isna()

       A      B
0  False  False
1  False   True
2   True  False
3  False   True
4  False  False

Counting missing values per column (absolute and percentage)

In [127]:
# Missing values per column (count)
df.isna().sum()

A    1
B    2
dtype: int64

In [128]:
# Missing values per column (percentage)
df.isna().mean()

A    0.2
B    0.4
dtype: float64

Filtering rows with missing values in specific columns

In [129]:
# Filter rows with missing values in column A
df[df['A'].isna()]

    A  B
2 NaN  C

In [130]:
# Filter rows with missing values in column B
df[df['B'].isna()]

     A     B
1  2.0  None
3  4.0  None

Filtering DataFrame rows using query() with conditions

query() filters a DataFrame using a string expression that evaluates to True or False, returning only the rows that meet the condition. It provides a cleaner and more readable alternative to traditional boolean indexing

In [131]:
prod.query('list_price > 5500')

,product_id,product_name,brand_id,category_id,model_year,list_price
49,50,Trek Silque SLR 7 Women's - 2017,9,7,2017,5999.99
50,51,Trek Silque SLR 8 Women's - 2017,9,7,2017,6499.99
148,149,Trek Domane SLR 8 Disc - 2018,9,7,2018,7499.99
154,155,Trek Domane SLR 9 Disc - 2018,9,7,2018,11999.99
155,156,Trek Domane SL Frameset - 2018,9,7,2018,6499.99
156,157,Trek Domane SL Frameset Women's - 2018,9,7,2018,6499.99
168,169,Trek Emonda SLR 8 - 2018,9,7,2018,6499.99

Filters rows using multiple conditions inside query() by combining logical operators (e.g., &) to return only rows where all conditions are True

In [132]:
prod.query('list_price > 5500 & model_year == 2018')

,product_id,product_name,brand_id,category_id,model_year,list_price
148,149,Trek Domane SLR 8 Disc - 2018,9,7,2018,7499.99
154,155,Trek Domane SLR 9 Disc - 2018,9,7,2018,11999.99
155,156,Trek Domane SL Frameset - 2018,9,7,2018,6499.99
156,157,Trek Domane SL Frameset Women's - 2018,9,7,2018,6499.99
168,169,Trek Emonda SLR 8 - 2018,9,7,2018,6499.99

Using external variables inside query()

In [133]:
preco = 5500
prod.query('list_price > @preco & model_year == 2018')

,product_id,product_name,brand_id,category_id,model_year,list_price
148,149,Trek Domane SLR 8 Disc - 2018,9,7,2018,7499.99
154,155,Trek Domane SLR 9 Disc - 2018,9,7,2018,11999.99
155,156,Trek Domane SL Frameset - 2018,9,7,2018,6499.99
156,157,Trek Domane SL Frameset Women's - 2018,9,7,2018,6499.99
168,169,Trek Emonda SLR 8 - 2018,9,7,2018,6499.99